[build]
builder = "DOCKERFILE"
dockerfilePath = "app/Dockerfile"
watchPatterns = ["app/**"]

[deploy]
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

